#!/usr/bin/env bash

set -eu
set -o pipefail

function main {
    ocamlbuild -use-ocamlfind -j 0 src/cats.cmxa
    ocamlbuild -use-ocamlfind -j 0 src/examples/ExCats.native
    ocamlbuild -use-ocamlfind -j 0 src/examples/Rose.native
    exit 0
}

main "${@}"
