#!/usr/bin/env bash

set -eu
set -o pipefail

function main {
    ocamlbuild -use-ocamlfind -j 0 src/prelude.cmxa
    ocamlbuild -use-ocamlfind -j 0 src/examples/ExPrelude.native
    exit 0
}

main "${@}"
