#!/usr/bin/env bash

set -eu
set -o pipefail

function main {
    ocamlbuild src/prelude.cmxa
    ocamlbuild src/implicits.cmxa
    ocamlbuild src/examples/ExPrelude.native
    ocamlbuild src/examples/ExImplicits.native
    exit 0
}

main "${@}"
